# Generated by Django 4.2.5 on 2023-11-10 19:57

import CurriculumVitae.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('CurriculumVitae', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='user',
            field=models.OneToOneField(default=CurriculumVitae.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to='User.customuser'),
        ),
        migrations.AlterField(
            model_name='curriculumvitae',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.customuser'),
        ),
    ]
