# Generated by Django 4.2.5 on 2023-11-12 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('CurriculumVitae', '0002_contactinfo_user_alter_curriculumvitae_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumvitae',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='User.customuser'),
        ),
    ]
