# Generated by Django 4.2.5 on 2023-11-13 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CurriculumVitae', '0005_remove_curriculumvitae_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumvitae',
            name='education',
        ),
        migrations.RemoveField(
            model_name='curriculumvitae',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='curriculumvitae',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='curriculumvitae',
            name='workexperience',
        ),
        migrations.AddField(
            model_name='education',
            name='curriculum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='CurriculumVitae.curriculumvitae'),
        ),
        migrations.AddField(
            model_name='interests',
            name='curriculum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='CurriculumVitae.curriculumvitae'),
        ),
        migrations.AddField(
            model_name='skills',
            name='curriculum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='CurriculumVitae.curriculumvitae'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='curriculum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workexperience', to='CurriculumVitae.curriculumvitae'),
        ),
    ]
