# Generated by Django 4.2.5 on 2023-11-17 04:25

import CurriculumVitae.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CurriculumVitae', '0008_alter_contactinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='user',
            field=models.OneToOneField(default=CurriculumVitae.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
