# Generated by Django 4.2.5 on 2023-11-21 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CurriculumVitae', '0009_alter_contactinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='CurriculumVitae.curriculumvitae'),
        ),
        migrations.AlterField(
            model_name='interests',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='CurriculumVitae.curriculumvitae'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='CurriculumVitae.curriculumvitae'),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='contact_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='CurriculumVitae.contactinfo'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workexperience', to='CurriculumVitae.curriculumvitae'),
        ),
    ]
